# Generated by Django 2.2.1 on 2019-06-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('Title', models.CharField(max_length=32)),
                ('Discription', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
