# Generated by Django 2.2.1 on 2019-06-19 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_todomodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='todomodel',
            name='time',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
